quizzes:
  - id: python
    title: Python Programming
    description: Basic Python programming skills test

  - id: data
    title: Data Manipulation
    description: Basic Numpy and Pandas

modules:
  - id: m1
    title: Casual Inference
    description: Required module for the CI lab
    quiz_ids:
      - python
