quizzes:
  - id: sample_quiz
    title: A sample quiz
    description: A demo quiz

  - id: python
    title: Python Programming
    description: Basic Python programming syntax

  - id: model_development
    title: Model Development
    description: Basic model development using Python

modules:
  - id: my_module
    title: Sample Module
    description: This module holds multiple quizzess
    quiz_ids:
      - sample_quiz
