quizzes:
  - id: sample_quiz
    title: A sample quiz
    description: A demo quiz

  - id: python
    title: Python Programming
    description: Basic python programming syntax

modules:
  - id: my_module
    title: Sample Module
    description: This module holds multiple quizzess
    quiz_ids:
      - sample_quiz
